### ISSUE TITLE
Filter does not support string array

### ISSUE THREAD

**Issue by asithade** [HubSpot/hubspot-api-nodejs#127]
I'm trying to get all deals associated with a company. I get all the IDs from the `associationsApi` and then I want to pass all the IDs to the deals search API to grab all those deals. When trying to send in an array of string IDs, I'm met with a couple of issues. 

1. Type definitions do not allow anything but strings to be passed in for value
2. When I updated the type def and passed in a string array, I get the following response from the API: 
`Error Invalid input JSON on line 1, column 39: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token`

```Typescript
  const companyDeals = await hubspotClient.crm.companies.associationsApi.getAll(data.id, 'deals');

  if (companyDeals.body.results.length === 0) {
    return [];
  }

  const dealFilters = companyDeals.body.results.map((deal) => deal.id);

  const deals = await hubspotClient.crm.deals.searchApi
    .doSearch({
      filterGroups: [
        {
          filters: [
            {
              propertyName: 'deal_id',
              operator: Filter.OperatorEnum.In,
              value: dealFilters // Type definitions does not allow for string array here
            }
          ]
        }
      ],
      sorts: ['string'],
      properties: ['dealname', 'dealstage'],
      limit: 10,
      after: 0
    })
    .catch((err) => {
      console.error('Error', err.response.body.message);
      return { body: err.response.body };
    });

  console.log(deals.body);

  return deals.body.results || deals.body.message;
```

**Comment by nomoney4me** [comment]
This might be because of the reason in https://github.com/HubSpot/hubspot-api-nodejs/issues/156.
I also added "values" to satisfy TS requirement but the .serialize() might be the one sending the values as undefined.

![image](https://user-images.githubusercontent.com/9965349/153619825-e3e62c1f-3d57-41d7-9551-7b6f812bc3b0.png)

**Comment by fdel-car** [comment]
Just bumped into this issue as well, hoping it will get fixed soon 😄

As a workaround, you can chain `filters` with the `EQ` operator like that:

```js
  const response = await client.crm.deals.searchApi
    .doSearch(
      {
        filterGroups: [
          // {
          //   filters: [
          //     {
          //       values: dealIds,
          //       propertyName: 'hs_object_id',
          //       operator: 'IN',
          //     },
          //   ],
          // },
          ...dealIds.map((id) => ({
            filters: [
              { value: id, propertyName: 'hs_object_id', operator: 'EQ' },
            ],
          })),
        ],
      }
    )
```

Be careful though because I think HubSpot allows up to 3 filter groups with up to 3 filters in each, thus in your scenario, the workaround probably isn't applicable 😕

**Comment by ksvirkou-hubspot** [comment]
Hi every one 
it is fixed 
Could you  check [the latest version of SDK](https://www.npmjs.com/package/@hubspot/api-client/v/6.0.1), please?
