### ISSUE TITLE
client.crm.deals.basicApi.getById always returns error

### ISSUE THREAD

**Issue by nixxle** [HubSpot/hubspot-api-nodejs#194]
Request:
 `await this.client.crm.deals.basicApi.getById(id)`

Result:
Error: The mediaType text/html is not supported by ObjectSerializer.parse.

**Comment by fmalk** [comment]
I was greeted by the same error just as I was starting with the SDK.
Eventually I downgraded to 5.0.0, because NPM currently searches for the beta install by default.
From #159 I gather that this error comes from the API returning an HTML (error) and we expect a JSON result.
I suggest you inspect your Hubspot app's logs and search for that /deals call. Your request went thru, it just did'nt return correctly. Most likely, it will show an error (ID not found).
From there, you can explore other calls, and see if with the correct ID you can make that deal call.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
I ve fixed it in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0)

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
I ve fixed it in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0)
now returns `ApiException [Error]: HTTP-Code: 404`
