### ISSUE TITLE
Several legacy dependencies that are bloating the code

### ISSUE THREAD

**Issue by darkmavis1980** [HubSpot/hubspot-api-nodejs#249]
There are several legacy and unnecessary libraries, such as `btoa` (which is imported by never used), `bluebird` (which has been deprecated 3 years ago), `lodash` that is used where simple ES6 syntax can do the same job.
We should cleanup the code to reduce the bloat of the code and remove now insecure and deprecated code.

What can be remove/optmized can be seen in this (now closed) PR https://github.com/HubSpot/hubspot-api-nodejs/pull/239

**Comment by ksvirkou-hubspot** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/14257

**Comment by ksvirkou-hubspot** [comment]
Hi @darkmavis1980 
I've done all сhanges besides "Replaced qs with more appropriate URLSearchParams" ([because querystring is more performant than URLSearchParams](https://nodejs.org/api/querystring.html)).
You may see my changes in [version 8.3.1](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.3.1).

**Comment by darkmavis1980** [comment]
Thanks for that @ksvirkou-hubspot 👍
