### ISSUE TITLE
hubspotClient doesn't update even after providing a new access token and fetches the previously provided access token and releavent data

### ISSUE THREAD

**Issue by shadab14meb346** [HubSpot/hubspot-api-nodejs#341]
The below function updates the refreshToken of my hubspotClient
```typescript
export const refreshAccessToken = async (refreshToken: string) => {
  const data = await hubspotClient.oauth.tokensApi.createToken(
    "refresh_token",
    undefined,
    undefined,
    process.env.HUB_SPOT_CLIENT_ID,
    process.env.HUB_SPOT_CLIENT_SECRET,
    refreshToken
  );
  hubspotClient.setAccessToken(data.accessToken);
  return data.accessToken;
};
```
Currently, each time I request to fetch some data from HubSpot I update the refresh token of the hubspotClient.
Everything works fine in the local machine but after I deploy it on AWS lambda the issue is even a new accessToken gives the data associated with the previously passed accessToken. 

To be sure that AWS lambada is not the culprit here I then tried to fetch the data from HubSpot using the REST API approach.
Below is the function which does this and it works perfectly fine in the local machine as well as in AWS lambda deployment.

```typescript
const getHubSpotDataUsingRestAPICall = async ({ accessToken, properties }) => {
  const options = {
    method: "GET",
    url: "https://api.hubspot.com/crm/v3/objects/contacts",
    params: { properties },
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    data: { count: 10, vidOffset: 0 },
  };
  const response = await axios.request(options);
  return response.data;
};
```

I am using this version `@hubspot/api-client": "^8.4.2"`.

**Comment by albertyfwu** [comment]
I am seeing this too. However, it doesn't work even locally for me.

While I don't totally understand what is happening, I believe this is due to https://github.com/HubSpot/hubspot-api-nodejs/commit/b807f38c39876a7fb8ff05655b9cb276c84d7c98

https://github.com/HubSpot/hubspot-api-nodejs/blob/master/src/services/ApiDecoratorService.ts#L34-L43

The decorator is doing some patching and there might be something off about the binding. If I just `return api`, the access token refresh is fixed. Also, if I first construct `new clientPrototype.constructor(configuration)` before patching, things are fixed as well.

cc @ksvirkou-hubspot

**Comment by jeffersonlipsky** [comment]
I confirm there is an issue. Like @albertyfwu said, it appears to be related to binding. The wrapped method contains the first accessToken set. I can't confirm, but I suspect the method gets called multiple times as the token is set since the init method gets called and the decorators get reset each time the accessToken is set.

I didn't need to downgrade; I simply removed the rate limiting properties (limiterOptions or numberOfApiCallRetries) when creating the client instance.
