### ISSUE TITLE
How can i make a note for a contact.

### ISSUE THREAD

**Issue by ohabash** [HubSpot/hubspot-api-nodejs#342]
When i send this request it works but i dont know where the note is getting saved cause it is not on the contact notes.

```
  createNote(options): Promise<any> {
	const properties = {
		hs_timestamp: new Date().toISOString(),
		hs_note_body: 'TESTING Spoke with decision maker john',
		hubspot_owner_id: '24141179'
	};
	console.log(`🚀 => HsObjects => createNote => properties:`, properties)
	const payload = {
		properties,
		associations: [
			{
				to: {
					id: '1882651' // this is the contact id
				},
				types: [
					{
						associationCategory: 'HUBSPOT_DEFINED',
						associationTypeId: 2 // 2 = contact is what i was hoping
					}
				]
			}
		]
	};
	return this.client.crm.objects.notes.basicApi.create(payload)
	.then(data => data)
	.catch((error) => this.handleError(error, 'hubspot.objects', 'createNote(...)'));
}
```

**Comment by ksvirkou-hubspot** [comment]
Hi @ohabash 
Now you we support only properties.
`associations` have been added a few days ago on Hubspot side and we are working on it now.

**Comment by romnzs** [comment]
First, what you need in `associationTypeId` is the id of the `note_to_contact` association type. You can get it with [CRM API | Associations](https://developers.hubspot.com/docs/api/crm/associations/v3) and it should be `202`. As I understand HubSpot defined association type ids are constant and not portal specific (cause I've found the list of ids for some common associations in [legacy docs](https://legacydocs.hubspot.com/docs/methods/crm-associations/crm-associations-overview)), so I assume you can just hardcode `202`.

However since currently the `apiRequest.crm.objects.notes.basicApi.create` uses only `properties` it will still not work for you (by the way that's why you have a note saved instead of getting a validation error). As a workaround you can use `client.apiRequest` instead, like this:
```js
return this.client
  .apiRequest({
    method: 'POST',
    path: '/crm/v3/objects/notes',
    body: payload,
  })
  .then(data => data)
  .catch((error) => this.handleError(error, 'hubspot.objects', 'createNote(...)'));
```

**Comment by ksvirkou-hubspot** [comment]
Regarding `associationTypeId` you can use `AssociationTypes` enum.

**Comment by ohabash** [comment]
Read the docs and this forum still dont know why 202 is the `associationTypeId ` for contacts. why cant the api just accepts `contact` and you guys resolve the id. Or at the very least provide a list of associationTypeIds.

**Comment by ohabash** [comment]
so how can i find out the `associationTypeId` for `note_to_contact`?  

Docs are not helping with the "how"

**Comment by OtavioCapila** [comment]
> so how can I find out the `associationTypeId` for `note_to_contact`?
> 
> Docs are not helping with the "how"

Try the code `202`. Hubspot documentation is a mess. It lacks a lot of information, I had to go to their Slack channel to ask for help a lot of times.

**Comment by ksvirkou-hubspot** [comment]
> so how can i find out the `associationTypeId` for `note_to_contact`?
> 
> Docs are not helping with the "how"

`AssociationTypes.noteToContact`

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've added `associations` property in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/9.0.0-beta.0).
