### ISSUE TITLE
Properties parameter not working as expected

### ISSUE THREAD

**Issue by JuanSpada** [HubSpot/hubspot-api-nodejs#347]
I am using the @hubspot/api-client library version 8.8.1 to make requests to the HubSpot API. I have noticed that when I set the properties parameter to undefined, the API returns all the properties for the specified object type. However, when I set the properties parameter to an array of property names, like "name, label", the API returns an error message that reads "TypeError: Cannot read properties of undefined (reading 'makeRequestContext')".

I have tested the same request using the HubSpot API documentation and confirmed that the request works as expected, returning only the specified properties.

Here is an example code snippet showing how I am making the request:

```
const objectType = "contacts";
const archived = false;
const properties = "name, label";

const allProperties = await hubspotClient.crm.properties.coreApi.getAll(
  objectType,
  archived,
  properties
);

console.log("Hubspot properties: ", allProperties);

```
If I set properties = undefined, it returns all properties. But if I try to filter them I  have that error message:
"Cannot read properties of undefined (reading 'makeRequestContext')"
I have also tested the same code on the official HubSpot API documentation page (https://developers.hubspot.com/docs/api/crm/properties), and the request works as expected, returning only the specified properties.

Please let me know if there is a known issue with the properties parameter or if there is anything I can do to work around this issue.

**Comment by romnzs** [comment]
Looks like `hubspotClient.crm.properties.coreApi.getAll` currently does not support specifying properties. The third parameter is for configuration options not for properties.

https://github.com/HubSpot/hubspot-api-nodejs/blob/dc6e93c0cda898188a0c181e9d0ca067835290b4/codegen/crm/properties/types/PromiseAPI.ts#L103-L112

To work around this (and similar) issue you can utilize the `apiRequest` method to make arbitrary calls to HubSpot API. In your case it would be:
```js
const objectType = "contacts";
const archived = false;
const properties = "name, label";

const response = await hubspotClient.apiRequest({
	method: 'GET',
	path: `/crm/v3/properties/${objectType}`,
	qs: {
		archived,
		properties,
	},
});

const allProperties = await response.json();

console.log("Hubspot properties: ", allProperties);
```

Also take note that you can omit `archived` param, since it's `false` by default.

**Comment by JuanSpada** [comment]
Thank you very much @romnzs. Your approach fixes my issue.
