### ISSUE TITLE
Incorrect List Membership Response Type

### ISSUE THREAD

**Issue by kevin-induro** [HubSpot/hubspot-api-nodejs#544]
The types indicate that the return for `crm.lists.membershipsApi.getPage` should be `CollectionResponseLong` i.e. that the results array of the response should be an array of numbers. Instead, as the API indicates, the results are an object of type:
```
{
  recordId: string;
  membershipTimestamp: Date;
}
```
Additionally, assuming this covers the API documented by [Fetch List Memberships Ordered by ID](https://developers.hubspot.com/beta-docs/reference/api/crm/lists#get-%2Fcrm%2Fv3%2Flists%2F%7Blistid%7D%2Fmemberships), a method for [Fetch List Memberships Ordered by Added to List Date](https://developers.hubspot.com/beta-docs/reference/api/crm/lists#get-%2Fcrm%2Fv3%2Flists%2F%7Blistid%7D%2Fmemberships%2Fjoin-order) is missing.

**Comment by ksvirkou-hubspot** [comment]
Hi @kevin-induro 
It has been fixed in [the latest version 12.0.1](https://www.npmjs.com/package/@hubspot/api-client/v/12.0.1).
Method `crm.lists.membershipsApi.getPage()` returns `ApiCollectionResponseJoinTimeAndRecordId` which contains a collection of `JoinTimeAndRecordId`.
https://github.com/HubSpot/hubspot-api-nodejs/blob/18c7c3816cde469463f75888c5d9d2fc985ff44c/codegen/crm/lists/models/JoinTimeAndRecordId.ts#L14-L16
 Method [Fetch List Memberships Ordered by Added to List Date](https://developers.hubspot.com/beta-docs/reference/api/crm/lists#get-%2Fcrm%2Fv3%2Flists%2F%7Blistid%7D%2Fmemberships%2Fjoin-order): `crm.lists.membershipsApi.getPageOrderedByAddedToListDate()`
Code examples in [the docs](https://developers.hubspot.com/beta-docs/reference/api/crm/lists) will be fixed soon.

**Comment by ksvirkou-hubspot** [comment]
The code examples in [the docs](https://developers.hubspot.com/beta-docs/reference/api/crm/lists) have been fixed.
